# =============================================================================
# RDS MODULE
#
# Deploys a managed relational database into the PRIVATE DATA TIER.
#
# SECURITY MODEL (the part that matters in an interview):
#   - publicly_accessible = false  -> no public IP is ever assigned.
#   - Subnets have NO route to NAT or IGW -> unreachable from the internet
#     and unable to initiate outbound internet traffic.
#   - The security group has NO ingress rule in this module. The caller
#     (the environment root module) adds a single rule allowing the ECS
#     security group. See the note on circular dependencies below.
#   - The password is GENERATED by Terraform and stored in Secrets Manager.
#     It is never written to a .tfvars file, never committed, and never
#     placed in a plaintext container environment variable.
#
# WHY THE INGRESS RULE LIVES IN THE ROOT MODULE:
#   RDS needs to allow the ECS security group -> rds depends on ecs.
#   ECS needs the Secrets Manager ARN from RDS -> ecs depends on rds.
#   That is a circular module dependency, which Terraform cannot resolve.
#   The standard fix is to break the cycle by declaring the cross-module
#   security group rule as a standalone resource in the calling root module.
# =============================================================================

locals {
  common_tags = merge(var.tags, { Module = "rds" })
}

# -----------------------------------------------------------------------------
# DB subnet group
# Tells RDS which subnets it may place the instance (and its standby) in.
# Must span at least two AZs, even for a single-AZ instance, because that is
# what makes a later Multi-AZ conversion or failover possible.
# -----------------------------------------------------------------------------
resource "aws_db_subnet_group" "this" {
  name        = "${var.name}-db-subnet-group"
  description = "Private data-tier subnets for ${var.name}"
  subnet_ids  = var.subnet_ids

  tags = merge(local.common_tags, { Name = "${var.name}-db-subnet-group" })
}

# -----------------------------------------------------------------------------
# Security group
#
# Deliberately created with NO ingress rules. Security groups DENY by default:
# an empty security group allows nothing inbound. The caller adds exactly one
# rule permitting the application tier.
#
# Egress: also none. The database has no reason to initiate connections.
# (Note: security groups are STATEFUL, so responses to allowed inbound
# connections flow back automatically without any egress rule.)
# -----------------------------------------------------------------------------
resource "aws_security_group" "this" {
  name        = "${var.name}-rds-sg"
  description = "RDS security group for ${var.name}. Ingress is added by the caller."
  vpc_id      = var.vpc_id

  tags = merge(local.common_tags, { Name = "${var.name}-rds-sg" })

  lifecycle {
    create_before_destroy = true
  }
}

# -----------------------------------------------------------------------------
# Password generation + storage
#
# random_password generates a value that IS stored in Terraform state.
# This is precisely why the state bucket is encrypted with KMS, versioned,
# and blocked from public access (see bootstrap/). State is sensitive data.
# -----------------------------------------------------------------------------
resource "random_password" "master" {
  length  = 32
  special = true
  # RDS rejects these characters in master passwords.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "db" {
  name        = "${var.name}/rds/master"
  description = "Master credentials for the ${var.name} RDS instance"

  # Days before a deleted secret is permanently removed. 0 = immediate.
  # Short in dev so re-creating the stack does not hit "secret already
  # scheduled for deletion"; production should keep a recovery window.
  recovery_window_in_days = 0

  tags = merge(local.common_tags, { Name = "${var.name}-rds-secret" })
}

# The secret VALUE is a separate resource — a secret can have many versions,
# which is what enables rotation without changing the ARN consumers use.
resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    username = var.username
    password = random_password.master.result
    engine   = var.engine
    host     = aws_db_instance.this.address
    port     = var.port
    dbname   = var.db_name
  })
}

# -----------------------------------------------------------------------------
# Enhanced Monitoring role (optional)
#
# Standard CloudWatch metrics are collected from the HYPERVISOR at 60s
# granularity. Enhanced Monitoring runs an agent INSIDE the DB host and
# reports OS-level metrics (per-process CPU, memory, disk I/O) at up to 1s.
# You need it to answer "which process is eating the CPU", which hypervisor
# metrics can never tell you.
# -----------------------------------------------------------------------------
data "aws_iam_policy_document" "monitoring_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "monitoring" {
  count = var.monitoring_interval > 0 ? 1 : 0

  name               = "${var.name}-rds-monitoring"
  assume_role_policy = data.aws_iam_policy_document.monitoring_assume.json
  tags               = local.common_tags
}

resource "aws_iam_role_policy_attachment" "monitoring" {
  count = var.monitoring_interval > 0 ? 1 : 0

  role       = aws_iam_role.monitoring[0].name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

# -----------------------------------------------------------------------------
# Parameter group
# Lets us change engine settings. We enable connection logging as a baseline
# audit control rather than accepting engine defaults blindly.
# -----------------------------------------------------------------------------
resource "aws_db_parameter_group" "this" {
  name_prefix = "${var.name}-"
  family      = var.family
  description = "Parameter group for ${var.name}"

  parameter {
    name  = "log_connections"
    value = "1"
  }

  parameter {
    name  = "log_disconnections"
    value = "1"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = local.common_tags
}

# -----------------------------------------------------------------------------
# The database instance
# -----------------------------------------------------------------------------
resource "aws_db_instance" "this" {
  identifier = "${var.name}-db"

  engine         = var.engine
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp3"

  # ENCRYPTION AT REST. Cannot be enabled on an existing unencrypted
  # instance — you would have to snapshot, copy the snapshot with
  # encryption, and restore. Always enable it from day one.
  storage_encrypted = true
  kms_key_id        = var.kms_key_arn

  db_name  = var.db_name
  username = var.username
  password = random_password.master.result
  port     = var.port

  # --- NETWORK ISOLATION ---
  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.this.id]
  publicly_accessible    = false # HARD REQUIREMENT
  # -------------------------

  multi_az = var.multi_az

  parameter_group_name = aws_db_parameter_group.this.name

  backup_retention_period = var.backup_retention_period
  backup_window           = var.backup_window
  maintenance_window      = var.maintenance_window
  copy_tags_to_snapshot   = true

  # Minor version patches applied automatically in the maintenance window.
  auto_minor_version_upgrade = true

  monitoring_interval = var.monitoring_interval
  monitoring_role_arn = var.monitoring_interval > 0 ? aws_iam_role.monitoring[0].arn : null

  performance_insights_enabled = var.performance_insights_enabled

  # Ship engine logs to CloudWatch so they survive instance replacement.
  enabled_cloudwatch_logs_exports = var.engine == "postgres" ? ["postgresql", "upgrade"] : ["error", "general", "slowquery"]

  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name}-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  apply_immediately = var.apply_immediately

  lifecycle {
    ignore_changes = [
      # The final snapshot name embeds a timestamp, which would otherwise
      # produce a spurious diff on every single plan.
      final_snapshot_identifier,
      # Engine minor version drifts due to auto_minor_version_upgrade.
      engine_version,
    ]
  }

  tags = merge(local.common_tags, { Name = "${var.name}-db" })
}
